const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .use("/img", express.static(__dirname + '/img'))
  .use("/js", express.static(__dirname + '/js'))
  .use("/css", express.static(__dirname + '/css'))
  .use("/test", express.static(__dirname + '/test'))
  .use('/lib', express.static(__dirname + '/node_modules'))
  .set('views', __dirname + '/public/views')
  .set('view engine', 'html')
  .engine('html', require('ejs').renderFile)
  .get('*', (req, res) => res.render('sudoku.html'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))